image: startup-script
tag: 62bfbe88c17778aad7bef9fa57ff9e2d4a9ba0d8

# Restart existing pods when initializing the node to force all pods being
# managed by Cilium (GKE, EKS)
restartPods: false

# Reconfigure Kubelet to run in CNI mode (GKE)
reconfigureKubelet: false

# Delete the cbr0 bridge if it exists (GKE)
removeCbrBridge: false

# Wait for the /var/run/azure-vnet.json file to be created before continuing the script
# This must be set as true explicitly if Azure AKS with CNI chaining is used.
expectAzureVnet: false

# Revert nodeinit changes via preStop container lifecycle hook
revertReconfigureKubelet: false

## Node tolerations for pod assignment on nodes with taints
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
tolerations:
- operator: Exists
